apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
      - image: "496157679619.dkr.ecr.us-east-1.amazonaws.com/vikashashoke:latest"
        name: kubernetes-configmap-reload
        ports:
        - containerPort: 8080
          name: http

